dist: xenial
language: minimal
jobs:
  include:
    - name: "Build Cydia Repos"
      script: "make"
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: false
        local_dir: build
        email: bot@nickt.dev
        on:
          branch: master
